[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.install]
cmds = [
  "npm ci",
  "cd client && rm -rf dist node_modules .vite && npm install && cd .."
]

[phases.build]
cmds = [
  "cd client && npm run build && cd ..",
  "mkdir -p /app/dist-built",
  "cp -r client/dist/* /app/dist-built/"
]

[start]
cmd = "node server.js"