[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm install",
  "cd client && npm install"
]

[phases.build]
cmds = [
  "cd client && npm run build"
]

[phases.build]
cmds = ["npm install", "npm run build"]
cacheDirectories = []

[start]
cmd = "npm start"